version: 2
updates:
- package-ecosystem: nuget
  directory: "/ServiceBackendConfigurationPlugin"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/ServiceBackendConfigurationPlugin.Integration.Test"
  schedule:
    interval: daily